name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Publish
      run: |
        git clone https://github.com/username/richmiles.github.io.git
        rm -rf richmiles.github.io/*
        cp -r dist/* richmiles.github.io/
        cd richmiles.github.io
        git add .
        git commit -m "Publishing new build"
        git push
